require("mason").setup()

-- Como hago instalar codelldb de forma autimatica?
--require("mason-nvim-dap").setup({
--    automatic_setup = true,
--   -- ensure_installed = { "codelldb" }
--})
--
--require 'mason-nvim-dap'.setup_handlers {
--    function(source_name)
--        -- all sources with no handler get passed here
--
--
--        -- Keep original functionality of `automatic_setup = true`
--        require('mason-nvim-dap.automatic_setup')(source_name)
--    end,
--    codelldb = function(source_name)
--        dap.configurations.cpp = {
--            {
--                name = "Launch",
--                type = "lldb",
--                request = "launch",
--                program = function()
--                    return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
--                end,
--                cwd = '${workspaceFolder}',
--                stopOnEntry = false,
--                args = {},
--                runInTerminal = true,
--            }
--        }
--    end,
--}
